font_family JetBrains Mono Nerd Font
bold_font auto
italic_font auto
font_size 13.0
background #000000
foreground #f5f5f5
selection_background #ffffff
selection_foreground #000000
cursor #ffffff
cursor_text_color #000000
background_opacity 0.78
window_padding_width 20
confirm_os_window_close 0
hide_window_decorations yes
enable_audio_bell no
visual_bell_duration 0
remember_window_size no
initial_window_width 1200
initial_window_height 700
shell_integration no-cursor
tab_bar_style hidden
active_border_color #ffffff
inactive_border_color #262626
