font_family JetBrains Mono
font_size 11.0
background #213f66
foreground #f4f7fb
cursor #ffffff
selection_background #5f92c8
selection_foreground #ffffff

dynamic_background_opacity yes
background_opacity 0.62
background_blur 1
window_padding_width 18
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0.0
inactive_text_alpha 0.84
shell_integration no-cursor
