debug {
    disable_logs = false
    enable_stdout_logs = true
}

env = LIBSEAT_BACKEND,seatd
env = XDG_CURRENT_DESKTOP,Hyprland

# disable the real host panel that leaks into the privileged container
monitor = eDP-1,disable

cursor {
    no_hardware_cursors = true
    no_warps = true
}

animations {
    enabled = false
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(cba6f7ff)
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
}

decoration {
    rounding = 8

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

input {
    kb_layout = us
    follow_mouse = 1
}

misc {
    disable_hyprland_qtutils_check = true
    vrr = 0
}

$term = foot
$menu = rofi -show drun

exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dunst
exec-once = swww init
exec-once = [workspace 1 silent] $term

bind = SUPER, Return, exec, $term
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = SUPER, E, exec, kitty

source = ~/.config/hypr/generated.conf
