windowrulev2 = float,class:^(preview-term)$
windowrulev2 = move 82 42,class:^(preview-term)$
windowrulev2 = size 750 420,class:^(preview-term)$
windowrulev2 = float,class:^(firefox)$
windowrulev2 = move 900 40,class:^(firefox)$
windowrulev2 = size 930 650,class:^(firefox)$
windowrulev2 = float,class:^(media-widget)$
windowrulev2 = move 900 730,class:^(media-widget)$
windowrulev2 = size 520 250,class:^(media-widget)$
windowrulev2 = float,class:^(date-widget)$
windowrulev2 = move 1450 730,class:^(date-widget)$
windowrulev2 = size 400 250,class:^(date-widget)$
windowrulev2 = pin,class:^(media-widget)$
windowrulev2 = pin,class:^(date-widget)$
windowrulev2 = noborder,class:^(media-widget)$
windowrulev2 = noborder,class:^(date-widget)$
windowrulev2 = noborder,class:^(preview-term)$
windowrulev2 = noborder,class:^(firefox)$
