debug {
    disable_logs = false
    enable_stdout_logs = true
}

env = LIBSEAT_BACKEND,seatd
env = XDG_CURRENT_DESKTOP,Hyprland
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_SIZE,24

monitor = eDP-1,disable

cursor {
    no_hardware_cursors = true
    no_warps = true
}

animations {
    enabled = false
}

general {
    gaps_in = 14
    gaps_out = 20
    border_size = 1
    col.active_border = rgba(ffffffff)
    col.inactive_border = rgba(4a4a4acc)
    resize_on_border = true
    layout = dwindle
}

dwindle {
    preserve_split = true
}

decoration {
    rounding = 18

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }
}

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

$term = kitty
$browser = firefox --new-window file:///home/hypruser/.config/hypr/startpage/index.html
$menu = rofi -show drun

exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swww init
exec-once = bash -lc 'sleep 1; swww img /home/hypruser/.config/hypr/wallpapers/minimal.ppm --resize stretch'
exec-once = waybar
exec-once = dunst
exec-once = bash -lc 'sleep 1; kitty --class preview-term --title preview-term sh -lc "fastfetch; printf \"\\n\"; exec bash"'
exec-once = bash -lc 'sleep 2; firefox --new-window file:///home/hypruser/.config/hypr/startpage/index.html'
exec-once = bash -lc 'sleep 2; kitty --class media-widget --title media-widget sh -lc "python $HOME/.config/hypr/scripts/media_widget.py"'
exec-once = bash -lc 'sleep 2; kitty --class date-widget --title date-widget sh -lc "python $HOME/.config/hypr/scripts/date_widget.py"'

bind = SUPER, Return, exec, $term
bind = SUPER, K, exec, $term
bind = ALT, Return, exec, $term
bind = , F1, exec, $term
bind = SUPER, B, exec, $browser
bind = ALT, B, exec, $browser
bind = , F2, exec, $browser
bind = SUPER, D, exec, $menu
bind = ALT, Space, exec, $menu
bind = , F3, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = SUPER, E, exec, $term
bind = , F5, exec, hyprctl reload

source = ~/.config/hypr/generated.conf
